### ISSUE TITLE
No such file or directory server.properties, no such file or directory start.mcfunction

### ISSUE THREAD

**Issue by ProfessorDragon** [Legacy-Edition-Minigames/Minigames#44]
I tried installing the new version of Legacy Edition Battle. It didn't work.
![image](https://user-images.githubusercontent.com/95201497/222950601-7ce3d889-dfb7-412d-9bdc-7f05d750eea9.png)
Apparently it failed to sync the MOTD, and also could not find server.properties or start.mcfunction.

**Comment by DBTDerpbox** [comment]
oh right, this is occurring due to the repository name change

**Comment by DBTDerpbox** [comment]
there's a development version you can use which "works"

download https://github.com/Legacy-Edition-Minigames/ToolBox/blob/git/LEB-ToolBox.py

run it using python, before installing change the branch to `testing`

run the installer, should work as normal

**Comment by ProfessorDragon** [comment]
Great, thanks, why was the repository renamed anyways?

**Comment by DBTDerpbox** [comment]
it was renamed due to being moved to an organization, and changed from `Legacy-Edition-Battle` to `Minigames` due to work on tumble being a thing

**Comment by ProfessorDragon** [comment]
Ah cool, I was hoping for glide but I guess that'll come eventually. Also this can be closed now if you want

**Comment by DBTDerpbox** [comment]
glide will be after tumble, though tumble has already had some work on it

glide will take a while due to how complicated it is, reaching parity with it won't be easy
