### ISSUE TITLE
Help me pls :(

### ISSUE THREAD

**Issue by Wabit02** [Legacy-Edition-Minigames/Minigames#45]
"Failed to load datapacks, can't proceed with server load. You can either fix your datapacks or reset to vanilla with --safeMode"
I Cant Start the server and i cant join to the DC server :( pls i love the legacy edtition minigames

**Comment by DBTDerpbox** [comment]
can you show the entire log? what branch and what toolbox version are you using?

**Comment by Wabit02** [comment]
can i pass you my discord to help me? pls wabit02#5127

**Comment by S-N00B-1** [comment]
Are you using [This](https://github.com/Legacy-Edition-Minigames/ToolBox/releases/tag/1.6) to install it, the vanilla client cannot run battle on its own.

**Comment by niceEli** [comment]
#49 #50

**Comment by DBTDerpbox** [comment]
closing this due to toolbox being rewritten
