### ISSUE TITLE
Music playing over each other in game 

### ISSUE THREAD

**Issue by Trunkis** [Legacy-Edition-Minigames/Minigames#47]
The music tracks play over other music tracks playing in a game. This happened when I was in a 3 round game.

**Comment by DBTDerpbox** [comment]
are you referring to multiple battle songs or battle songs playing over survival Minecraft tracks?

**Comment by Trunkis** [comment]
Multiple battle tracks playing at once

**Comment by DBTDerpbox** [comment]
Was this on a toolbox server? if so what commit is it running on? the commit hash can be seen on the MOTD (message displayed in the multiplayer menu)

**Comment by Trunkis** [comment]
I was hosting it using the leb toolbox and it was on commit c36f69

**Comment by DBTDerpbox** [comment]
do you have any mods on your client? if possible listing them would be helpful

**Comment by Trunkis** [comment]
I did not have any mods on my client it was base 1.19.2

**Comment by DBTDerpbox** [comment]
interesting, this is the first case I've seen of this occurring on vanilla

**Comment by DBTDerpbox** [comment]
marking this as help wanted due to nobody else being able to recreate the issue

**Comment by DBTDerpbox** [comment]
Closing this as not a single person has managed to replicate this bug, given this happened during the hiatus this was likely in the old toolbox build anyways which was broken anyways
